name: Prettier

on:
  push:
    paths:
      - '**.*js*'
      - '**.*ts*'
      - '**.css'
      - '**.less'
      - '**.scss'
      - '**.html'
      - '**.hbs'
      - '**.json'
      - '**.gql'
      - '**.graphql'
      - '**.md*'
      - '**.yaml'
      - '**.yml'
  pull_request_target:
    paths:
      - '**.*js*'
      - '**.*ts*'
      - '**.css'
      - '**.less'
      - '**.scss'
      - '**.html'
      - '**.hbs'
      - '**.json'
      - '**.gql'
      - '**.graphql'
      - '**.md*'
      - '**.yaml'
      - '**.yml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prettier:
    runs-on: ubuntu-latest
    if: github.actor != 'demosjarco-prettier[bot]'
    permissions:
      contents: write
    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          disable-sudo-and-containers: true
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
      - uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b # v2.1.1
        id: gh_prettier_token
        with:
          app-id: ${{ vars.GH_PRETTIER_CLIENT_ID }}
          private-key: ${{ secrets.GH_PRETTIER_PRIVATE_KEY }}
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{ steps.gh_prettier_token.outputs.token }}
      - name: Git Setup
        if: steps.changes.outputs.changes == 'true'
        run: |
          git config user.name "${{ steps.gh_prettier_token.outputs.app-slug }}[bot]"
          git config user.email "${{ vars.GH_PRETTIER_USER_ID }}+${{ steps.gh_prettier_token.outputs.app-slug }}[bot]@users.noreply.github.com"
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
      - run: npm ci --ignore-scripts --include-workspace-root
      - run: npm run-script install --if-present --include-workspace-root
      - run: npm run fmt:fix
      - name: Check for Changes
        id: changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
      - run: git commit -am "Ran formatter" || echo "No formatting done"
        if: steps.changes.outputs.changes == 'true'
      - run: git push
        if: steps.changes.outputs.changes == 'true'
